### ISSUE TITLE
MadeHub v0.2 To-Does

### ISSUE THREAD

**Issue by Felli** [GreenVolume/humhub-themes-MadeHub#18]
The following are what needs fixed within MadeHub.
- [ ] Pagination #17
- [x] Custom Menu  https://github.com/GreenVolume/humhub-themes-MadeHub/issues/15#issuecomment-301213986
- [x] Clean up CSS & LESS files #23
- [x] Implement better scrolling for both Web & Mobile #54
- [x] Fix call to LanguageChooser.php #48
- [x] Fix https://github.com/GreenVolume/humhub-themes-MadeHub/issues/18#issuecomment-294364040
- [ ] CSS Positioning Issues #75
- [ ] SCSS Version Issues (Confirmed) #81

**Comment by Felli** [comment]
## Fixed
```
Error: Class 'yii\helper\Html' not found in /home/futayuri/community.futayuriverse.com/themes/MadeHub/views/admin/setting/design.php:68 Stack trace:
#0 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/View.php(328): require()
#1 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/futayuri/...', Array)
#2 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/futayuri/...', Array, Object(humhub\modules\admin\controllers\SettingController))
#3 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('design', Array, Object(humhub\modules\admin\controllers\SettingController))
#4 /home/futayuri/community.futayuriverse.com/protected/humhub/modules/admin/controllers/SettingController.php(205): yii\base\Controller->render('design', Array)
#5 [internal function]: humhub\modules\admin\controllers\SettingController->actionDesign()
#6 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('design', Array)
#9 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/setting/d...', Array)
#10 /home/futayuri/community.futayuriverse.com/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)
 #11 /home/futayuri/community.futayuriverse.com/index.php(25): yii\base\Application->run()
#12 {main}
```
